---
apiVersion: v1
kind: pod
metadata:
  name: postgres-pod
  labels:
    author: akashdaida
    name: postgres
spec:
  containers:
    - name: mydb
      image: postgres
      ports:
        -container: 5432
      env:
        - name: POSTGRES_PASSWORD
          value: akashdaida
        - name: POSTGRES_DB
          value: mydb
        - name: POSTGRES_USER
          value: myuser
...
