---
apiVersion: v1
kind: pod
metadata:
  name: worker-app-pod
  labels:
    author: akashdaida
    name: worker-app
spec:
  containers:
    - name: worker-app
      image: dockersamples/examplevotingapp_worker
...

